export const API_CONFIG = {
  OPENAI_API_KEY: process.env.NEXT_PUBLIC_OPENAI_API_KEY || '',
  OPENAI_MODEL: 'gpt-4-turbo-preview',
  OPENAI_TEMPERATURE: 0.7,
  OPENAI_MAX_TOKENS: 2000,
  GEMINI_API_KEY: process.env.NEXT_PUBLIC_GEMINI_API_KEY || '',
  GEMINI_MODEL: 'gemini-2.0-flash',
  GEMINI_TEMPERATURE: 0.8,
  GEMINI_MAX_TOKENS: 1500,
  CLAUDE_API_KEY: process.env.NEXT_PUBLIC_CLAUDE_API_KEY || '',
  CLAUDE_MODEL: 'claude-3-opus-20240229',
  CLAUDE_TEMPERATURE: 0.5,
  CLAUDE_MAX_TOKENS: 1024,
}; 